// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dart:convert';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Object? handleSerdeJsonValueTwinSync({required Object? val}) => RustLib
    .instance
    .api
    .crateApiPseudoManualSerdeJsonTypeTwinSyncHandleSerdeJsonValueTwinSync(
      val: val,
    );

Object? handleOptionSerdeJsonValueTwinSync({Object? val}) => RustLib
    .instance
    .api
    .crateApiPseudoManualSerdeJsonTypeTwinSyncHandleOptionSerdeJsonValueTwinSync(
      val: val,
    );

List<Object?> handleVecSerdeJsonValueTwinSync({
  required List<Object?> val,
}) => RustLib.instance.api
    .crateApiPseudoManualSerdeJsonTypeTwinSyncHandleVecSerdeJsonValueTwinSync(
      val: val,
    );

Map<String, Object?> handleMapSerdeJsonValueTwinSync({
  required Map<String, Object?> val,
}) => RustLib.instance.api
    .crateApiPseudoManualSerdeJsonTypeTwinSyncHandleMapSerdeJsonValueTwinSync(
      val: val,
    );

FeatureSerdeJsonTwinSync handleNestedSerdeJsonValueTwinSync({
  required FeatureSerdeJsonTwinSync wrapper,
}) => RustLib.instance.api
    .crateApiPseudoManualSerdeJsonTypeTwinSyncHandleNestedSerdeJsonValueTwinSync(
      wrapper: wrapper,
    );

class FeatureSerdeJsonTwinSync {
  final Object? data;

  const FeatureSerdeJsonTwinSync({required this.data});

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeatureSerdeJsonTwinSync &&
          runtimeType == other.runtimeType &&
          data == other.data;
}
