- Desdaemon: Support not only simple enums but also enums with fields which gets translated to native enum or sealed freezed class in Dart. Support the Option type as nullable types in Dart. Support Vec of Strings type. Support tuple type. Support comments in code. Add marker attributes for future usage. Add Linux and Windows support for with-flutter example, and make CI works for that. Avoid parameter collision. Overhaul the documentation and add several chapters to demonstrate configuring a Flutter+Rust project in all five platforms. Refactor command module. Precompiled binary CI workflow. Fix bugs. Add support for the Web platform, parallel to the existing mobile/desktop platforms, via WASM and JavaScript as intermediate values. GitHub retry actions. Implement draft of opaque types. Refactor Boxed and Option. Impl list of dates and optionals. Parameter defaults. Refactor CLI. Refactor codegen errors. Refactor for performance.
- rogurotus: Add Rust opaque types, enabling arbitrary Rust structs to be used as opaque Dart objects by generating wrappers and raw Arc pointers. Also add Dart opaque types, allowing to use any Dart objects in Rust code. Extend `SyncReturn` for more types. Fix generation bug. Fix SyncReturn. Migrate to dart-sys. Update CI. Fix linters. Fix SyncReturn bug.
- ngasull: Make sync mode support whatever types that classical async mode supports. Bump sdk.
- SecondFlight: Allow structs and enums to be imported from other files within the crate by creating source graph. Auto-create relevant dir. Fix `store_dart_post_cobject` error with ffigen 6.0.
- lattice0: Implement hierarchy of exceptions. Support methods, such that Rust struct impls can be converted to Dart class methods. StreamSink at any argument.
- Unoqwy: Add struct mirrors, such that types in the external crates can be imported and used without redefining and copying.
- antonok-edm: Avoid converting syn types to strings before parsing to improve code and be more robust.
- sagudev: Make code generator a `lib`. Add error types. Depend on `cbindgen`. Fix LLVM paths. Update deps. Fix CI errors.
- surban: Support unit return type. Skip unresolvable modules. Ignore prefer_const_constructors. Non-final Dart fields.
- Roms1383: Fix build_runner calling bug. Remove global `ffigen` dependency. Improve version check. Fix enum name-variant conflicts. Support Chrono date time and UUID types. Migrate to Rust 1.64 workspace. Update and refactor CI. Update header comments. Code cleanup.
- dbsxdbsx: Allow generating multiple Rust and Dart files. Fix lint. Update doc. Add logging. Loosen config. Prefix methods.
- GregoryConrad: Add doc to setup frb inside a Dart/Flutter library.
- huang12zheng: Support type aliases and nested ones. Tweak code generation. Fix rust_build_and_test on Mac. Improve CI logic and cache. Remove bridge field in model.
- trobanga: Add support for `[T;N]` structs. Add `usize` support. Add a cmd argument. Separate dart tests. Fix fallible list case. Fix test compile. Fix Result + RustAutoOpaque.
- MnlPhlp: Support macros and will auto expand. Allow mirror types in streams.
- SoLongAndThanksForAllThePizza: Refactor and enhance SyncReturn to support more types. Refactor post-release CI.
- hsfzxjy: Fix SyncReturn use-after-free bug.
- Cupnfish: Support arrays as function parameters. Allow multi mirror.
- alanlzhang: Add generation for Dart metadata. Enhance and fix module parser. Fix enum in struct. Fix linter. Improve hints.
- erikas-taroza: Support list of primitive enums. Make enum camelCase. Warn wrong path. Fix cargo expand.
- AlexV525: Add version check skipper. Add Dart fix. Fix folder. Update CI. Use Melos.
- alexthe2: Add Option Datetime. Add empty structs. Improve doc. Add `r#`. Fix mirror enum bug. Bump version.
- patmuk: Set MSRV. Fail fast. Improve message. Support relative config. Improve multiple docs. Fix warning. Fix CI.
- SiongSng: Finish implementing exception hierarchy. Fix SyncReturn bug.
- JustSimplyKyle: Also finish implementing exception hierarchy. Allow ignore function.
- Zaitam: Fix when method return struct. Partial migration to Dart 3.
- coder0xff: Discuss binding unmodified Rust. Refactor SupportedInnerType. Extra codegen tester.
- NobodyForNothing: Support impl-for partially.
- nitn3lav: Nested `struct`s without `Box`.
- aran: Fix map + mirror. Fix pubspec. Upgrde ffigen. Replace to js_interop. Bump version. Fix typo. Configure opaque impl.
- mcmah309: Add cli plugin scaffold generation.
- AlienKevin: Add flutter example for macOS. Add doc for Android NDK bug. Improve migration doc.
- Larpoux: Fix async generation. Update web-audio-api binding.
- banool: Fix pubspec parsing. Fix symbol-stripping doc.
- alexlapa: Fix Dart_PostCObject. Fix DartOpaque.
- kyrias: Use portable atomic. Ignore accessor fields. Update doc.
- Integral-Tech: Use concat. Fix lint.
- Tienisto: Remove default enum case. Add mock init.
- satvikpendem: 'Add json_serializable. Update CI. Little co-work #989.'
- anlumo: Fix freezed + methods. Non-clone RustOpaque. Update syn. Support custom hasher.
- temeddix: Fix broken CI. Custom num workers. Fix MacOS doc steps. Update doc. Make zero-copy defaultable.
- NightFeather0615: Fix Vec bool.
- fmeef: Add cargo feature flag.
- ski0090: Fix folder creation.
- borgoat: Upgrade freezed.
- xuwaters: Support edition 2024.
- SirKrlos: Fix fvm calls.
- OfficialBoyfriend: Fix error display.
- jippeholwerda: Fix raw identifier.
- PaulGrandperrin: Fix lint.
- iazel: Fix lint.
- wxitcode: Add org option. Support MacOS log. Fix a typo.
- atezet: Upgrade dependencies. Follow rustfmt.
- evdokimovs: Change dependencies.
- Markus43: Fix folder removal.
- Krysl: Add preamble.
- Vollbrecht: Warn absolute path.
- w-ensink: Improve doc. Fix CI. Refactor. Add tests.
- smw-wagnerma: Improve Windows encoding handling.
- powpingdone: Document JNI init and libc++_static linking.
- debanjanbasu: Document alternative NDK init.
- valeth: Rename callFfi's port.
- sccheruku: Prevent double-generating utility.
- upsuper: Refactor delegate-attr.
- jsonmona: Add import.
- MateusHBR: Add pub get.
- codercengiz: Fix mirroring bug.
- Michael-F-Bryan: Detect broken bindings.
- phlip9: Fix no-serde compilation.
- SilverMira: Fix StreamSink.
- h3x4d3c1m4l: Fix when outside folder.
- HalidOdat: Improve config method. Hint build.rs.
- Berrysoft: Fix missing symbols.
- bus710: Add a case in troubleshooting.
- Demezy: Mention troubleshooting.
- gutenfries: Bump proc-macros.
- anstadnik: Check keywords.
- syndim: Add a bracket to box.
- vhdirk: Support dashed crate.
- akkumar: External traits doc.
- rhian-cs: Add Cargo workspace doc.
- TENX-S: Improve doc. Reproduce a bug.
- CJBuchel: Remove throw.
- polypixeldev: Improve doc.
- CicadaCinema: Bump version. Improve doc.
- CosmicHorrorDev: Change deps.
- akashgurava: Partial fix.
- w1th0utnam3: Improve message.
- vincent-herlemont: Loosen version.
- canxin121: Fix permission.
- pixelshot91: Update cargokit. Fix doc link.
- TrackerSB: Bump allo-isolate.
- bubnov: Improve doc.
- Dampfwalze: Improve doc.
- samuel-cavalcanti: Improve doc.
- zaynetro: Improve doc.
- raphaelrobert: Remove oudated doc.
- DMouayad: Improve doc.
- elliotsayes: Improve doc.
- tmpfs: Improve doc.
- thomas725: Improve doc.
- juzi5201314: Improve doc.
- Voklen: Improve doc.
- svenstaro: Improve doc.
- utilForever: Fix typos.
- not-holar: Fix typos.
- Stonks3141: Fix doc credit.
- mattiasgronlund: Bump version.
- adsouza: Fix doc grammar.
- vimaxwell: Fix doc link.
- lker-dev: Fix doc link.
- jaiakash: Fix doc link.
- feber: Fix doc link.
- adam-huganir: Fix a typo.
- ernstvanderlinden: Fix a typo.
- damywise: Fix a typo.
- rustui: Fix a typo.
- escwxyz: Fix a typo.
- eltociear: Fix a typo.
- thesimplekid: Fix a typo.
