name: dart_workspace
publish_to: none
environment:
  sdk: ^3.9.0

workspace:
  - web_one
  - flutter_two

dev_dependencies:
  melos: ^7.1.0


melos:
  scripts:
    # TODO: What type of target will be useful for the internal test tool here?
    web_one:
      description: Run Web One.
      run: cd web_one && flutter run -d chrome
    flutter_two:
      description: Run Flutter Two.
      run: cd flutter_two && flutter run -d chrome

    generate:
      description: Run code generation for all packages.
      run: melos exec -c 6 --fail-fast -- "flutter_rust_bridge_codegen generate"