// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'misc_example.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<EnumSimpleTwinNormal> funcEnumSimpleTwinNormal(
        {required EnumSimpleTwinNormal arg}) =>
    RustLib.instance.api.crateApiEnumerationFuncEnumSimpleTwinNormal(arg: arg);

Future<EnumWithItemMixedTwinNormal> funcEnumWithItemMixedTwinNormal(
        {required EnumWithItemMixedTwinNormal arg}) =>
    RustLib.instance.api
        .crateApiEnumerationFuncEnumWithItemMixedTwinNormal(arg: arg);

Future<EnumWithItemTupleTwinNormal> funcEnumWithItemTupleTwinNormal(
        {required EnumWithItemTupleTwinNormal arg}) =>
    RustLib.instance.api
        .crateApiEnumerationFuncEnumWithItemTupleTwinNormal(arg: arg);

Future<EnumWithItemStructTwinNormal> funcEnumWithItemStructTwinNormal(
        {required EnumWithItemStructTwinNormal arg}) =>
    RustLib.instance.api
        .crateApiEnumerationFuncEnumWithItemStructTwinNormal(arg: arg);

Future<EnumWithDiscriminantTwinNormal> funcEnumWithDiscriminantTwinNormal(
        {required EnumWithDiscriminantTwinNormal arg}) =>
    RustLib.instance.api
        .crateApiEnumerationFuncEnumWithDiscriminantTwinNormal(arg: arg);

Future<Uint8List> printNoteTwinNormal({required NoteTwinNormal note}) =>
    RustLib.instance.api.crateApiEnumerationPrintNoteTwinNormal(note: note);

Future<WeekdaysTwinNormal?> handleReturnEnumTwinNormal(
        {required String input}) =>
    RustLib.instance.api
        .crateApiEnumerationHandleReturnEnumTwinNormal(input: input);

Future<WeekdaysTwinNormal> handleEnumParameterTwinNormal(
        {required WeekdaysTwinNormal weekday}) =>
    RustLib.instance.api
        .crateApiEnumerationHandleEnumParameterTwinNormal(weekday: weekday);

Future<MeasureTwinNormal?> multiplyByTenTwinNormal(
        {required MeasureTwinNormal measure}) =>
    RustLib.instance.api
        .crateApiEnumerationMultiplyByTenTwinNormal(measure: measure);

Future<KitchenSinkTwinNormal> handleEnumStructTwinNormal(
        {required KitchenSinkTwinNormal val}) =>
    RustLib.instance.api
        .crateApiEnumerationHandleEnumStructTwinNormal(val: val);

sealed class DistanceTwinNormal {
  const DistanceTwinNormal._();

  const factory DistanceTwinNormal.unknown() = DistanceTwinNormal_Unknown;
  const factory DistanceTwinNormal.map(
    double field0,
  ) = DistanceTwinNormal_Map;
}

class DistanceTwinNormal_Unknown extends DistanceTwinNormal {
  const DistanceTwinNormal_Unknown() : super._();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DistanceTwinNormal_Unknown && runtimeType == other.runtimeType;
}

class DistanceTwinNormal_Map extends DistanceTwinNormal {
  final double field0;

  const DistanceTwinNormal_Map(
    this.field0,
  ) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DistanceTwinNormal_Map &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

enum EnumSimpleTwinNormal {
  a,
  b,
  ;
}

enum EnumWithDiscriminantTwinNormal {
  oneHundred,
  fifty,
  ;
}

sealed class EnumWithItemMixedTwinNormal {
  const EnumWithItemMixedTwinNormal._();

  const factory EnumWithItemMixedTwinNormal.a() = EnumWithItemMixedTwinNormal_A;
  const factory EnumWithItemMixedTwinNormal.b(
    Uint8List field0,
  ) = EnumWithItemMixedTwinNormal_B;
  const factory EnumWithItemMixedTwinNormal.c({
    required String cField,
  }) = EnumWithItemMixedTwinNormal_C;
}

class EnumWithItemMixedTwinNormal_A extends EnumWithItemMixedTwinNormal {
  const EnumWithItemMixedTwinNormal_A() : super._();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemMixedTwinNormal_A &&
          runtimeType == other.runtimeType;
}

class EnumWithItemMixedTwinNormal_B extends EnumWithItemMixedTwinNormal {
  final Uint8List field0;

  const EnumWithItemMixedTwinNormal_B(
    this.field0,
  ) : super._();

  @override
  int get hashCode => const DeepCollectionEquality().hash(field0);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemMixedTwinNormal_B &&
          runtimeType == other.runtimeType &&
          const DeepCollectionEquality().equals(field0, other.field0);
}

class EnumWithItemMixedTwinNormal_C extends EnumWithItemMixedTwinNormal {
  final String cField;

  const EnumWithItemMixedTwinNormal_C({
    required this.cField,
  }) : super._();

  @override
  int get hashCode => cField.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemMixedTwinNormal_C &&
          runtimeType == other.runtimeType &&
          cField == other.cField;
}

sealed class EnumWithItemStructTwinNormal {
  const EnumWithItemStructTwinNormal._();

  const factory EnumWithItemStructTwinNormal.a({
    required Uint8List aField,
  }) = EnumWithItemStructTwinNormal_A;
  const factory EnumWithItemStructTwinNormal.b({
    required Int32List bField,
  }) = EnumWithItemStructTwinNormal_B;
}

class EnumWithItemStructTwinNormal_A extends EnumWithItemStructTwinNormal {
  final Uint8List aField;

  const EnumWithItemStructTwinNormal_A({
    required this.aField,
  }) : super._();

  @override
  int get hashCode => const DeepCollectionEquality().hash(aField);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemStructTwinNormal_A &&
          runtimeType == other.runtimeType &&
          const DeepCollectionEquality().equals(aField, other.aField);
}

class EnumWithItemStructTwinNormal_B extends EnumWithItemStructTwinNormal {
  final Int32List bField;

  const EnumWithItemStructTwinNormal_B({
    required this.bField,
  }) : super._();

  @override
  int get hashCode => const DeepCollectionEquality().hash(bField);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemStructTwinNormal_B &&
          runtimeType == other.runtimeType &&
          const DeepCollectionEquality().equals(bField, other.bField);
}

sealed class EnumWithItemTupleTwinNormal {
  const EnumWithItemTupleTwinNormal._();

  const factory EnumWithItemTupleTwinNormal.a(
    Uint8List field0,
  ) = EnumWithItemTupleTwinNormal_A;
  const factory EnumWithItemTupleTwinNormal.b(
    int field0,
  ) = EnumWithItemTupleTwinNormal_B;
}

class EnumWithItemTupleTwinNormal_A extends EnumWithItemTupleTwinNormal {
  final Uint8List field0;

  const EnumWithItemTupleTwinNormal_A(
    this.field0,
  ) : super._();

  @override
  int get hashCode => const DeepCollectionEquality().hash(field0);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemTupleTwinNormal_A &&
          runtimeType == other.runtimeType &&
          const DeepCollectionEquality().equals(field0, other.field0);
}

class EnumWithItemTupleTwinNormal_B extends EnumWithItemTupleTwinNormal {
  final int field0;

  const EnumWithItemTupleTwinNormal_B(
    this.field0,
  ) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumWithItemTupleTwinNormal_B &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

sealed class KitchenSinkTwinNormal {
  const KitchenSinkTwinNormal._();

  /// Comment on variant
  const factory KitchenSinkTwinNormal.empty() = KitchenSinkTwinNormal_Empty;
  const factory KitchenSinkTwinNormal.primitives({
    /// Dart field comment
    int int32,
    required double float64,
    required bool boolean,
  }) = KitchenSinkTwinNormal_Primitives;
  const factory KitchenSinkTwinNormal.nested(
    int field0, [
    KitchenSinkTwinNormal field1,
  ]) = KitchenSinkTwinNormal_Nested;
  const factory KitchenSinkTwinNormal.optional([
    /// Comment on anonymous field
    int? field0,
    int? field1,
  ]) = KitchenSinkTwinNormal_Optional;
  const factory KitchenSinkTwinNormal.buffer(
    Uint8List field0,
  ) = KitchenSinkTwinNormal_Buffer;
  const factory KitchenSinkTwinNormal.enums([
    WeekdaysTwinNormal field0,
  ]) = KitchenSinkTwinNormal_Enums;
}

class KitchenSinkTwinNormal_Empty extends KitchenSinkTwinNormal {
  const KitchenSinkTwinNormal_Empty() : super._();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Empty && runtimeType == other.runtimeType;
}

class KitchenSinkTwinNormal_Primitives extends KitchenSinkTwinNormal {
  /// Dart field comment
  final int int32;
  final double float64;
  final bool boolean;

  const KitchenSinkTwinNormal_Primitives({
    this.int32 = -1,
    required this.float64,
    required this.boolean,
  }) : super._();

  @override
  int get hashCode => int32.hashCode ^ float64.hashCode ^ boolean.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Primitives &&
          runtimeType == other.runtimeType &&
          int32 == other.int32 &&
          float64 == other.float64 &&
          boolean == other.boolean;
}

class KitchenSinkTwinNormal_Nested extends KitchenSinkTwinNormal {
  final int field0;
  final KitchenSinkTwinNormal field1;

  const KitchenSinkTwinNormal_Nested(
    this.field0, [
    this.field1 = const KitchenSinkTwinNormal.empty(),
  ]) : super._();

  @override
  int get hashCode => field0.hashCode ^ field1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Nested &&
          runtimeType == other.runtimeType &&
          field0 == other.field0 &&
          field1 == other.field1;
}

class KitchenSinkTwinNormal_Optional extends KitchenSinkTwinNormal {
  /// Comment on anonymous field
  final int? field0;
  final int? field1;

  const KitchenSinkTwinNormal_Optional([
    this.field0 = -1,
    this.field1,
  ]) : super._();

  @override
  int get hashCode => field0.hashCode ^ field1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Optional &&
          runtimeType == other.runtimeType &&
          field0 == other.field0 &&
          field1 == other.field1;
}

class KitchenSinkTwinNormal_Buffer extends KitchenSinkTwinNormal {
  final Uint8List field0;

  const KitchenSinkTwinNormal_Buffer(
    this.field0,
  ) : super._();

  @override
  int get hashCode => const DeepCollectionEquality().hash(field0);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Buffer &&
          runtimeType == other.runtimeType &&
          const DeepCollectionEquality().equals(field0, other.field0);
}

class KitchenSinkTwinNormal_Enums extends KitchenSinkTwinNormal {
  final WeekdaysTwinNormal field0;

  const KitchenSinkTwinNormal_Enums([
    this.field0 = WeekdaysTwinNormal.sunday,
  ]) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KitchenSinkTwinNormal_Enums &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

sealed class MeasureTwinNormal {
  const MeasureTwinNormal._();

  const factory MeasureTwinNormal.speed(
    SpeedTwinNormal field0,
  ) = MeasureTwinNormal_Speed;
  const factory MeasureTwinNormal.distance(
    DistanceTwinNormal field0,
  ) = MeasureTwinNormal_Distance;
}

class MeasureTwinNormal_Speed extends MeasureTwinNormal {
  final SpeedTwinNormal field0;

  const MeasureTwinNormal_Speed(
    this.field0,
  ) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeasureTwinNormal_Speed &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class MeasureTwinNormal_Distance extends MeasureTwinNormal {
  final DistanceTwinNormal field0;

  const MeasureTwinNormal_Distance(
    this.field0,
  ) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MeasureTwinNormal_Distance &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class NoteTwinNormal {
  final WeekdaysTwinNormal day;
  final String body;

  const NoteTwinNormal({
    this.day = WeekdaysTwinNormal.sunday,
    required this.body,
  });

  @override
  int get hashCode => day.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteTwinNormal &&
          runtimeType == other.runtimeType &&
          day == other.day &&
          body == other.body;
}

sealed class SpeedTwinNormal {
  const SpeedTwinNormal._();

  const factory SpeedTwinNormal.unknown() = SpeedTwinNormal_Unknown;
  const factory SpeedTwinNormal.gps(
    double field0,
  ) = SpeedTwinNormal_GPS;
}

class SpeedTwinNormal_Unknown extends SpeedTwinNormal {
  const SpeedTwinNormal_Unknown() : super._();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTwinNormal_Unknown && runtimeType == other.runtimeType;
}

class SpeedTwinNormal_GPS extends SpeedTwinNormal {
  final double field0;

  const SpeedTwinNormal_GPS(
    this.field0,
  ) : super._();

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpeedTwinNormal_GPS &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}
