// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<int> minimalAdder({required int a, required int b}) =>
    RustLib.instance.api.crateApiMinimalMinimalAdder(a: a, b: b);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MyStruct>>
abstract class MyStruct implements RustOpaqueInterface {
  Future<String> exampleAsyncFuture();

  Future<String> exampleAsyncFuture2();

  Future<String> exampleAsyncMethod();

  Future<void> exampleInstanceMethod();

  static Future<void> exampleStaticMethod() =>
      RustLib.instance.api.crateApiMinimalMyStructExampleStaticMethod();
}

abstract class MyAsyncTrait {
  Future<Uint8List> exampleAsyncMethod(
      {required int argOne, required int argTwo, required List<int> argThree});
}

enum MyErr {
  oops,
  ;
}
