// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.38.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<int> minimalAdder({required int a, required int b}) =>
    RustLib.instance.api.crateApiMinimalMinimalAdder(a: a, b: b);

Future<void> f({required MyStruct a, required List<String> b}) =>
    RustLib.instance.api.crateApiMinimalF(a: a, b: b);

class MyStruct {
  final String field;

  const MyStruct({
    required this.field,
  });

  @override
  int get hashCode => field.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyStruct &&
          runtimeType == other.runtimeType &&
          field == other.field;
}
