// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.30.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::rust_async::RwLock<OpaqueStructWithDartCodeTwinSync>>
@sealed
class OpaqueStructWithDartCodeTwinSync extends RustOpaque {
  OpaqueStructWithDartCodeTwinSync.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  OpaqueStructWithDartCodeTwinSync.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib.instance.api
        .rust_arc_increment_strong_count_OpaqueStructWithDartCodeTwinSync,
    rustArcDecrementStrongCount: RustLib.instance.api
        .rust_arc_decrement_strong_count_OpaqueStructWithDartCodeTwinSync,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_OpaqueStructWithDartCodeTwinSyncPtr,
  );

  int normalMethodTwinSync({dynamic hint}) =>
      RustLib.instance.api.opaqueStructWithDartCodeTwinSyncNormalMethodTwinSync(
        that: this,
        hint: hint,
      );
}

class TranslatableStructWithDartCodeTwinSync {
  final int a;

  const TranslatableStructWithDartCodeTwinSync({
    required this.a,
  });

  int normalMethodTwinSync({dynamic hint}) => RustLib.instance.api
          .translatableStructWithDartCodeTwinSyncNormalMethodTwinSync(
        that: this,
        hint: hint,
      );

  @override
  bool operator ==(StructWithDartCodeTwinSync other) => a == other.a;

  @override
  int get hashCode => a.hashCode;

  int dartCodeMethod() => a * 2;
}
