// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

import 'dart:io';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'dart:convert';
import 'package:decimal/decimal.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<Object?> handleSerdeJsonValueTwinSse({required Object? val}) =>
    RustLib.instance.api
        .crateApiPseudoManualSerdeJsonTypeTwinSseHandleSerdeJsonValueTwinSse(
            val: val);

Future<Object?> handleOptionSerdeJsonValueTwinSse({Object? val}) => RustLib
    .instance.api
    .crateApiPseudoManualSerdeJsonTypeTwinSseHandleOptionSerdeJsonValueTwinSse(
        val: val);

Future<List<Object?>> handleVecSerdeJsonValueTwinSse(
        {required List<Object?> val}) =>
    RustLib.instance.api
        .crateApiPseudoManualSerdeJsonTypeTwinSseHandleVecSerdeJsonValueTwinSse(
            val: val);

Future<Map<String, Object?>> handleMapSerdeJsonValueTwinSse(
        {required Map<String, Object?> val}) =>
    RustLib.instance.api
        .crateApiPseudoManualSerdeJsonTypeTwinSseHandleMapSerdeJsonValueTwinSse(
            val: val);

Future<FeatureSerdeJsonTwinSse> handleNestedSerdeJsonValueTwinSse(
        {required FeatureSerdeJsonTwinSse wrapper}) =>
    RustLib.instance.api
        .crateApiPseudoManualSerdeJsonTypeTwinSseHandleNestedSerdeJsonValueTwinSse(
            wrapper: wrapper);

Future<FeatureBigNumberTwinSse> handleBigNumberTypesTwinSse(
        {required FeatureBigNumberTwinSse input}) =>
    RustLib.instance.api
        .crateApiPseudoManualSerdeJsonTypeTwinSseHandleBigNumberTypesTwinSse(
            input: input);

class FeatureBigNumberTwinSse {
  final BigInt signed;
  final BigInt unsigned;
  final BigInt reexportedSigned;
  final BigInt reexportedUnsigned;
  final Decimal decimal;
  final Decimal bigDecimal;

  const FeatureBigNumberTwinSse({
    required this.signed,
    required this.unsigned,
    required this.reexportedSigned,
    required this.reexportedUnsigned,
    required this.decimal,
    required this.bigDecimal,
  });

  @override
  int get hashCode =>
      signed.hashCode ^
      unsigned.hashCode ^
      reexportedSigned.hashCode ^
      reexportedUnsigned.hashCode ^
      decimal.hashCode ^
      bigDecimal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeatureBigNumberTwinSse &&
          runtimeType == other.runtimeType &&
          signed == other.signed &&
          unsigned == other.unsigned &&
          reexportedSigned == other.reexportedSigned &&
          reexportedUnsigned == other.reexportedUnsigned &&
          decimal == other.decimal &&
          bigDecimal == other.bigDecimal;
}

class FeatureSerdeJsonTwinSse {
  final Object? data;

  const FeatureSerdeJsonTwinSse({
    required this.data,
  });

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeatureSerdeJsonTwinSse &&
          runtimeType == other.runtimeType &&
          data == other.data;
}
