name: frb_example_pure_dart_pde
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  benchmark_harness: ^2.2.2
  meta: ^1.8.0
  lints: ^5.1.1
  flutter_rust_bridge:
    path: ../../frb_dart
  flutter_rust_bridge_utils:
    path: ../../frb_utils
  mocktail: ^1.0.1
  vm_service: ^13.0.0
  freezed_annotation: ^2.2.0
  js: ^0.6.5
  test: ^1.21.4
  uuid: ^4.1.0
  collection: ^1.16.0
  protobuf: ^3.1.0 # `protobuf` is only used for comparison
  json_annotation: ^4.9.0
dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.1.0+1
  ffigen: ^15.0.0
  json_serializable: ^6.9.3
