name: frb_example_gallery
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  lints: ^6.1.0
  rust_builder:
    path: rust_builder
  flutter_rust_bridge:
    path: ../../frb_dart
  freezed_annotation: ^3.0.0
  json_annotation: ^4.11.0
dev_dependencies:
  test: ^1.24.0
  freezed: ^3.2.5
  build_runner: ^2.13.1
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true
