// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/minimal.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  StructOneWithTraitTwinNormal
      dco_decode_box_autoadd_struct_one_with_trait_twin_normal(dynamic raw);

  @protected
  StructTwoWithTraitTwinNormal
      dco_decode_box_autoadd_struct_two_with_trait_twin_normal(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  StructOneWithTraitTwinNormal dco_decode_struct_one_with_trait_twin_normal(
      dynamic raw);

  @protected
  StructTwoWithTraitTwinNormal dco_decode_struct_two_with_trait_twin_normal(
      dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  StructOneWithTraitTwinNormal
      sse_decode_box_autoadd_struct_one_with_trait_twin_normal(
          SseDeserializer deserializer);

  @protected
  StructTwoWithTraitTwinNormal
      sse_decode_box_autoadd_struct_two_with_trait_twin_normal(
          SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  StructOneWithTraitTwinNormal sse_decode_struct_one_with_trait_twin_normal(
      SseDeserializer deserializer);

  @protected
  StructTwoWithTraitTwinNormal sse_decode_struct_two_with_trait_twin_normal(
      SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_box_autoadd_struct_one_with_trait_twin_normal(
      StructOneWithTraitTwinNormal self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_struct_two_with_trait_twin_normal(
      StructTwoWithTraitTwinNormal self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_struct_one_with_trait_twin_normal(
      StructOneWithTraitTwinNormal self, SseSerializer serializer);

  @protected
  void sse_encode_struct_two_with_trait_twin_normal(
      StructTwoWithTraitTwinNormal self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
