name: frb_example_dart_build_rs
description: flutter rust bridge example
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  lints: ^2.0.1
  flutter_rust_bridge:
    path: ../../frb_dart
  flutter_rust_bridge_utils:
    path: ../../frb_utils
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
dev_dependencies:
  test: ^1.21.4
  freezed: ^2.1.0+1
  build_runner: ^2.4.4
  ffigen: ^11.0.0
  json_serializable: ^6.9.0
