// NOTE: This file is mimicking how a human developer writes tests,
// and is auto-generated by frb_internal
// Please do not modify manually, but modify the origin and re-run frb_internal generator

import 'package:frb_example_pure_dart/src/rust/api/pseudo_manual/basic_map.dart';
import 'package:frb_example_pure_dart/src/rust/frb_generated.dart';
import 'package:test/test.dart';
import '../../test_utils.dart';
import 'dart:typed_data';

Future<void> main({bool skipRustLibInit = false}) async {
  if (!skipRustLibInit) await RustLib.init();

  group('basic_map', () {
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeI8TwinNormal, [0, -128, 127]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeI16TwinNormal, [0, -32768, 32767]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeI32TwinNormal, [0, -2147483648, 2147483647]);
    addTestsIdentityFunctionCall(exampleBasicMapTypeI64TwinNormal,
        [0, -9007199254740992, 9007199254740992]);
    addTestsIdentityFunctionCall(exampleBasicMapTypeU8TwinNormal, [0, 255]);
    addTestsIdentityFunctionCall(exampleBasicMapTypeU16TwinNormal, [0, 65535]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeU32TwinNormal, [0, 4294967295]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeU64TwinNormal, [0, 9007199254740992]);
    addTestsIdentityFunctionCall(exampleBasicMapTypeIsizeTwinNormal,
        [0, -2147483648, 2147483647, -9007199254740992, 9007199254740992]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeUsizeTwinNormal, [0, 4294967295, 9007199254740992]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeF32TwinNormal, [0, -42.5, 123456]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeF64TwinNormal, [0, -42.5, 123456]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeBoolTwinNormal, [false, true]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeStringTwinNormal, ["", "hello", "😂"]);
    addTestsIdentityFunctionCall(exampleBasicMapTypeBytesTwinNormal, [
      Uint8List.fromList([]),
      Uint8List.fromList([255, 0]),
      Uint8List.fromList([10, 20, 30, 40])
    ]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeBasicPrimitiveEnumTwinNormalTwinNormal, [
      BasicPrimitiveEnumTwinNormal.apple,
      BasicPrimitiveEnumTwinNormal.orange
    ]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeBasicGeneralEnumTwinNormalTwinNormal, [
      BasicGeneralEnumTwinNormal.apple(field: "one"),
      BasicGeneralEnumTwinNormal.orange()
    ]);
    addTestsIdentityFunctionCall(
        exampleBasicMapTypeBasicStructTwinNormalTwinNormal, [
      BasicStructTwinNormal(apple: null, orange: null),
      BasicStructTwinNormal(apple: "one", orange: 42)
    ]);
  });
}
