/// NOTE: This file is auto-generated by frb_internal. Please do not manually modify it.

import 'package:flutter_rust_bridge_utils/flutter_rust_bridge_utils_web.dart';
import 'dart_valgrind_test_entrypoint.dart' as dart_valgrind_test_entrypoint;

Future<void> main() async {
  await dartWebTestEntrypoint(() async {
    await dart_valgrind_test_entrypoint.main();
  });
}
