generate-advantages:
    just _inkscape-export advantages 500 310

_inkscape-export stem w h:
    /Applications/Inkscape.app/Contents/MacOS/inkscape --export-filename="{{stem}}.png" "{{stem}}.svg" -w {{w}} -h {{h}}
