name: Security Audit

on:
  push:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "**/deny.toml"
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  advisories_and_sources:
    name: Advisories and Sources
    timeout-minutes: 1
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-deny
      - run: cargo deny check advisories sources
